language: node_js
node_js:
  - 10
  - 8
before_install:
  - npm install --global npm@6.4.0
  - npm --version
jobs:
  include:
    - stage: deploy
      if: branch = master
      script: bash ./scripts/deploy.sh
