language: node_js
node_js:
  - 12
  - 10
  - 8
before_install:
  - npm install --global npm@6.4.0
  - npm --version
install:
  - npm install
  - npm install -g codecov
jobs:
  include:
    - stage: test
      script: bash ./scripts/test.sh
    # - stage: deploy
    #   if: branch = master
    #   script: bash ./scripts/deploy.sh
