language: node_js
node_js:
  - 10
  - 8
  - 6
before_install:
  - npm install --global npm@6.4.0
  - npm --version
jobs:
  include:
    - stage: eslint
      script: npm run test-eslint
    - stage: jshint
      script: npm run test-jshint